### ISSUE TITLE
Fix link in Binder button to point to this repository's master

### ISSUE THREAD

**Issue by simeoncarstens** [simeoncarstens/pandemic-sim#6]
Currently, the Binder button links to @truatpasteurdotfr's fork and thus does not reflect my latest refactoring and changes to the notebook. Thus, either the link or @truatpasteurdotfr's fork should be updated.
@truatpasteurdotfr: would you be ok with the Binder button using this repository instead of yours? I don't want to steal any credit, that's why I'm asking.

**Comment by truatpasteurdotfr** [comment]
sure, your work! remove my link and uncomment yours :D
